#配置数据库的连接信息
spring:
  application:
    name: tlias-web-management
  #配置数据库连接信息
  datasource:
#    url: jdbc:mysql://localhost:3306/tlias
#    url: jdbc:mysql://192.168.100.128:3306/tlias
    url: jdbc:mysql://mysql:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小(包括所有文件和表单数据)
      max-request-size: 100MB

#配置mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
    level:
      org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云相关的数据统一配置
aliyun:
    oss:
      endpoint: http://oss-cn-beijing.aliyuncs.com
      bucketName: java-aixs
      region: cn-beijing
